CREATE TABLE runtime_setting (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key TEXT NOT NULL,
    setting_value TEXT NOT NULL,
    value_type TEXT NOT NULL,
    scope TEXT NOT NULL DEFAULT 'GLOBAL',
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    effective_from TEXT,
    effective_to TEXT,
    updated_at TEXT NOT NULL,
    updated_by TEXT,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_runtime_setting_key_scope UNIQUE (setting_key, scope)
);

CREATE INDEX idx_runtime_setting_active
ON runtime_setting(is_active);

CREATE INDEX idx_runtime_setting_scope
ON runtime_setting(scope);

INSERT INTO runtime_setting
(setting_key, setting_value, value_type, scope, description, is_active, updated_at, updated_by, version)
VALUES
('angelone.login.time', '08:55', 'TIME', 'GLOBAL', 'Broker login start time', TRUE, now()::text, 'system', 0),
('websocket.connect.time', '09:10', 'TIME', 'GLOBAL', 'WebSocket connect time', TRUE, now()::text, 'system', 0),
('websocket.subscribe.mode', '1', 'INTEGER', 'GLOBAL', 'Angel One subscription mode', TRUE, now()::text, 'system', 0),
('websocket.disconnect.time', '15:31', 'TIME', 'GLOBAL', 'WebSocket disconnect time', TRUE, now()::text, 'system', 0),
('angelone.disconnect.time', '15:40', 'TIME', 'GLOBAL', 'Broker disconnect time', TRUE, now()::text, 'system', 0),
('housekeeping.time', '05:30', 'TIME', 'GLOBAL', 'Daily housekeeping start time', TRUE, now()::text, 'system', 0),
('retention.candles.days', '30', 'INTEGER', 'GLOBAL', 'Retention window for intraday candles', TRUE, now()::text, 'system', 0),
('retention.live.signals.days', '30', 'INTEGER', 'GLOBAL', 'Retention window for live signals', TRUE, now()::text, 'system', 0);