CREATE TABLE live_feed_state (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    exchange TEXT NOT NULL,
    trading_date TEXT NOT NULL,
    last_tick_time TEXT,
    last_tick_minute TEXT,
    last_checked_minute TEXT,
    blocked BOOLEAN NOT NULL DEFAULT FALSE,
    gap_from TEXT,
    gap_to TEXT,
    updated_at TEXT NOT NULL,
    CONSTRAINT uq_live_feed_state_symbol_exchange_date
        UNIQUE (symbol, exchange, trading_date)
);

CREATE INDEX idx_live_feed_state_date
    ON live_feed_state(trading_date);

CREATE INDEX idx_live_feed_state_blocked
    ON live_feed_state(blocked);



