CREATE TABLE live_minute_resolution (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    exchange TEXT NOT NULL,
    minute_time TEXT NOT NULL,
    trading_date TEXT NOT NULL,
    status TEXT NOT NULL,
    reason TEXT,
    resolved_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT uq_live_minute_resolution_symbol_exchange_minute
        UNIQUE (symbol, exchange, minute_time)
);

CREATE INDEX idx_live_minute_resolution_date
    ON live_minute_resolution(trading_date);

CREATE INDEX idx_live_minute_resolution_status
    ON live_minute_resolution(status);



