CREATE TABLE eod_data_entry (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    exchange TEXT NOT NULL,
    trading_date TEXT NOT NULL,
    status TEXT NOT NULL,
    expected_minute_count INTEGER,
    actual_minute_count INTEGER,
    no_trade_minute_count INTEGER,
    unresolved_minute_count INTEGER,
    repaired_minute_count INTEGER,
    reconciled_minute_count INTEGER,
    source TEXT NOT NULL,
    pipeline_version TEXT NOT NULL,
    started_at TEXT,
    completed_at TEXT,
    last_error TEXT,
    updated_at TEXT NOT NULL,
    CONSTRAINT uq_eod_data_entry_symbol_exchange_date
        UNIQUE (symbol, exchange, trading_date)
);

CREATE INDEX idx_eod_data_entry_date
    ON eod_data_entry(trading_date);

CREATE INDEX idx_eod_data_entry_status
    ON eod_data_entry(status);

CREATE INDEX idx_eod_data_entry_symbol_date
    ON eod_data_entry(symbol, exchange, trading_date);



