CREATE TABLE instrument_master (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    exchange TEXT NOT NULL,
    company_name TEXT NOT NULL,
    instrument_type TEXT NOT NULL DEFAULT 'EQUITY',
    segment TEXT NOT NULL DEFAULT 'CASH',
    broker_symbol TEXT,
    broker_token TEXT,
    isin TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_instrument_master_symbol_exchange UNIQUE (symbol, exchange),
    CONSTRAINT ck_instrument_master_exchange CHECK (exchange IN ('NSE'))
);

CREATE INDEX idx_instrument_master_symbol ON instrument_master(symbol);
CREATE INDEX idx_instrument_master_exchange_symbol ON instrument_master(exchange, symbol);
CREATE INDEX idx_instrument_master_active ON instrument_master(is_active);
CREATE INDEX idx_instrument_master_broker_token ON instrument_master(broker_token);