CREATE TABLE daily_stock_context (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    exchange TEXT NOT NULL,
    trading_date TEXT NOT NULL,

    first_candle_open DOUBLE PRECISION,
    first_candle_high DOUBLE PRECISION,
    first_candle_low DOUBLE PRECISION,
    first_candle_close DOUBLE PRECISION,
    first_candle_volume BIGINT,
    first_candle_range DOUBLE PRECISION,
    first_candle_range_pct DOUBLE PRECISION,
    first_candle_ready BOOLEAN NOT NULL DEFAULT FALSE,

    opening_range_high DOUBLE PRECISION,
    opening_range_low DOUBLE PRECISION,
    opening_range_size DOUBLE PRECISION,
    opening_range_size_pct DOUBLE PRECISION,
    opening_range_ready BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,

    CONSTRAINT uq_daily_stock_context UNIQUE (symbol, exchange, trading_date)
);

CREATE INDEX idx_daily_stock_context_trading_date
ON daily_stock_context(trading_date);

CREATE INDEX idx_daily_stock_context_symbol_date
ON daily_stock_context(symbol, trading_date);