CREATE TABLE runtime_setting (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    value TEXT NOT NULL,
    value_type TEXT NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TEXT NOT NULL DEFAULT now()::text
);

CREATE INDEX idx_runtime_setting_name
ON runtime_setting(name);

CREATE INDEX idx_runtime_setting_active
ON runtime_setting(is_active);

INSERT INTO runtime_setting (name, value, value_type, description, is_active, updated_at)
VALUES
('angelone.login.time', '08:50', 'TIME', 'Time to initiate automated broker login before market open', TRUE, now()::text),
('websocket.connect.time', '09:15', 'TIME', 'Time to connect WebSocket and subscribe to active stocks', TRUE, now()::text),
('websocket.disconnect.time', '15:40', 'TIME', 'Time to gracefully disconnect WebSocket after market close', TRUE, now()::text),
('angelone.disconnect.time', '17:00', 'TIME', 'Time to close broker session after post-market reconciliation', TRUE, now()::text),
('housekeeping.time', '05:30', 'TIME', 'Daily morning cleanup start time for old logs and temporary data', TRUE, now()::text),
('market.open.time', '09:15', 'TIME', 'Official NSE market session open time', TRUE, now()::text),
('market.close.time', '15:30', 'TIME', 'Official NSE market session close time', TRUE, now()::text),
('websocket.subscribe.mode', '3', 'INTEGER', 'Angel One stream depth mode (1=LTP, 2=Quote, 3=SnapQuote)', TRUE, now()::text),
('websocket.idle.close.minutes', '10', 'INTEGER', 'Inactivity threshold in minutes before closing idle WebSocket', TRUE, now()::text),
('websocket.stale.ticks.minutes', '2', 'INTEGER', 'Threshold in minutes without ticks before marking feed stale', TRUE, now()::text),
('retention.candles.days', '30', 'INTEGER', 'Retention window in days for 1-minute intraday market candles', TRUE, now()::text),
('retention.live.signals.days', '30', 'INTEGER', 'Retention window in days for live generated scanner signals', TRUE, now()::text),
('validation.max.price.spike', '0.40', 'DOUBLE', 'Maximum allowable single-candle price variation (40%)', TRUE, now()::text),
('validation.min.price', '0.01', 'DOUBLE', 'Minimum valid equity price threshold', TRUE, now()::text),
('feed.health.check.interval.ms', '15000', 'INTEGER', 'Feed health monitor polling interval in milliseconds', TRUE, now()::text),
('alert.stale.ticks.minutes', '10', 'INTEGER', 'Inactive threshold before sending feed alert notification', TRUE, now()::text)
ON CONFLICT (name) DO NOTHING;