CREATE TABLE market_minute_snapshot (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    exchange TEXT NOT NULL,
    minute_time TEXT NOT NULL,
    latest_tick_time TEXT NOT NULL,
    trading_date TEXT NOT NULL,
    broker_token TEXT,
    subscription_mode INTEGER,
    exchange_type INTEGER,
    last_price DOUBLE PRECISION,
    last_traded_quantity BIGINT,
    average_traded_price DOUBLE PRECISION,
    volume_traded_for_day BIGINT,
    total_buy_quantity BIGINT,
    total_sell_quantity BIGINT,
    open_interest BIGINT,
    open_interest_change_percent DOUBLE PRECISION,
    upper_circuit_limit DOUBLE PRECISION,
    lower_circuit_limit DOUBLE PRECISION,
    fifty_two_week_high_price DOUBLE PRECISION,
    fifty_two_week_low_price DOUBLE PRECISION,
    last_traded_timestamp_epoch BIGINT,
    exchange_timestamp_epoch BIGINT,
    sequence_number BIGINT,
    is_finalized BOOLEAN NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT uq_market_minute_snapshot_symbol_exchange_minute
        UNIQUE (symbol, exchange, minute_time)
);

CREATE INDEX idx_market_minute_snapshot_trading_date_minute
    ON market_minute_snapshot(trading_date, minute_time);

CREATE INDEX idx_market_minute_snapshot_updated_at
    ON market_minute_snapshot(updated_at);

CREATE INDEX idx_market_minute_snapshot_broker_token_minute
    ON market_minute_snapshot(broker_token, minute_time);