ALTER TABLE daily_stock_context
ADD COLUMN context_status TEXT NOT NULL DEFAULT 'PARTIAL';

CREATE TABLE daily_data_status (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    exchange TEXT NOT NULL,
    trading_date TEXT NOT NULL,
    status TEXT NOT NULL,
    expected_candle_count INTEGER,
    actual_candle_count INTEGER,
    missing_candle_count INTEGER,
    reason TEXT,
    updated_at TEXT NOT NULL,
    CONSTRAINT uq_daily_data_status_symbol_exchange_date
        UNIQUE (symbol, exchange, trading_date)
);

CREATE INDEX idx_daily_data_status_date_status
    ON daily_data_status(trading_date, status);

CREATE INDEX idx_daily_data_status_symbol_date
    ON daily_data_status(symbol, trading_date);

