CREATE TABLE daily_candle_summary (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    exchange TEXT NOT NULL,
    trading_date TEXT NOT NULL,
    expected_count INTEGER NOT NULL,
    actual_count INTEGER NOT NULL,
    missing_count INTEGER NOT NULL,
    duplicate_detected BOOLEAN NOT NULL,
    unfinalized_detected BOOLEAN NOT NULL,
    data_status TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT uq_daily_candle_summary_symbol_exchange_date
        UNIQUE (symbol, exchange, trading_date)
);

CREATE INDEX idx_daily_candle_summary_date
    ON daily_candle_summary(trading_date);

CREATE INDEX idx_daily_candle_summary_status
    ON daily_candle_summary(data_status);
