CREATE TABLE backfill_job (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    exchange TEXT NOT NULL,
    trading_date TEXT NOT NULL,
    priority INTEGER NOT NULL,
    status TEXT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    last_attempt_at TEXT,
    next_attempt_at TEXT NOT NULL,
    last_error TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT uq_backfill_job_symbol_exchange_date
        UNIQUE (symbol, exchange, trading_date)
);

CREATE INDEX idx_backfill_job_claim
    ON backfill_job(status, next_attempt_at, priority);

CREATE INDEX idx_backfill_job_stale
    ON backfill_job(status, last_attempt_at);



