CREATE TABLE workflow_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    workflow_id UUID NOT NULL UNIQUE,
    name TEXT NOT NULL,
    workflow_group TEXT NOT NULL,
    process_date TEXT,

    depends_on_workflow_id UUID,

    status TEXT NOT NULL DEFAULT 'READY',

    insert_timestamp TEXT NOT NULL DEFAULT now(),
    update_timestamp TEXT NOT NULL DEFAULT now(),

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    attempt_count INTEGER NOT NULL DEFAULT 0,

    message TEXT,
    error_details TEXT,

    version INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT fk_workflow_status_dependency
        FOREIGN KEY (depends_on_workflow_id)
        REFERENCES workflow_status(workflow_id),

    CONSTRAINT ck_workflow_status_status
        CHECK (status IN (
            'READY',
            'RUNNING',
            'SUCCESS',
            'FAILED',
            'SKIPPED'
        )),

    CONSTRAINT ck_workflow_status_attempt_count
        CHECK (attempt_count >= 0)
);

CREATE INDEX idx_workflow_status_group_status
    ON workflow_status(workflow_group, status);

CREATE INDEX idx_workflow_status_process_date
    ON workflow_status(process_date);

CREATE INDEX idx_workflow_status_date_group_status
    ON workflow_status(process_date, workflow_group, status);

CREATE INDEX idx_workflow_status_dependency
    ON workflow_status(depends_on_workflow_id);

CREATE INDEX idx_workflow_status_active
    ON workflow_status(is_active);